baseURL = 'https://ioky.fi/'
languageCode = 'fi'
title = 'Itäharjun Omakotiyhdistys'

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[menus]
  [[menus.main]]
    name = 'Etusivu'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Jäseneksi'
    pageRef = '/jaseneksi'
    weight = 20
  [[menus.main]]
    name = 'Säännöt'
    pageRef = '/saannot'
    weight = 30
  [[menus.main]]
    name = 'Tapahtumat'
    pageRef = '/tapahtumat'
    weight = 40
  [[menus.main]]
    name = 'Vuosikokoukset'
    pageRef = '/vuosikokoukset'
    weight = 50
  [[menus.main]]
    name = 'Usein kysyttyä'
    pageRef = '/usein-kysyttya'
    weight = 60
  [[menus.main]]
    name = 'Yhteydenotto'
    pageRef = '/yhteydenotto'
    weight = 70

[params]
  description = 'Itäharjun Omakotiyhdistys ry — Tälpual jokke vuadest 1916'
  footerCredit = 'Latenssi'
  footerCreditEmail = 'webmaster@latenssi.fi'
